/**
 * Generated by tsnapi — public API snapshot of `rolldown-plugin-dts`
 */
// #region Interfaces
export interface Logger {
  info: (..._: any[]) => void;
  warn: (..._: any[]) => void;
  error: (..._: any[]) => void;
}
export interface Options extends GeneralOptions, TscOptions {
  oxc?: boolean | Omit<IsolatedDeclarationsOptions, "sourcemap">;
  tsgo?: boolean | TsgoOptions;
  volarPlugin?: VolarPlugin;
}
// #endregion

// #region Functions
export declare function createFakeJsPlugin({ sourcemap, cjsDefault, sideEffects }: Pick<OptionsResolved, "sourcemap" | "cjsDefault" | "sideEffects">): Plugin;
export declare function createGeneratePlugin(_: Pick<OptionsResolved, "generator" | "entry" | "cwd" | "tsconfig" | "tsconfigRaw" | "build" | "incremental" | "oxc" | "emitDtsOnly" | "volarContext" | "parallel" | "eager" | "tsgo" | "newContext" | "emitJs" | "sourcemap" | "logger">): Plugin;
export declare function dts(_?: Options): Plugin[];
export declare function resolveOptions(_: Options): OptionsResolved;
// #endregion